const USD_TO_ARS = 1590;
const WHATSAPP_NUMBER = "5491100000000"; // Reemplazar por el número real de LclipStore.
const products = [
  {id:'ip18pm',brand:'iPhone',model:'iPhone 18 Pro Max',new:true,offer:true,variants:[
    {storage:'256GB',color:'Burgundy',hex:'#6e2631',price:1860,old:1999,stock:true,img:'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-18-pro-max-finish-select-burgundy-202609?wid=1600&hei=1600&fmt=png-alpha'},
    {storage:'256GB',color:'Black',hex:'#222',price:1830,stock:true,img:'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-18-pro-max-finish-select-black-202609?wid=1600&hei=1600&fmt=png-alpha'},
    {storage:'256GB',color:'Silver',hex:'#ddd',price:1830,stock:true,img:'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-18-pro-max-finish-select-silver-202609?wid=1600&hei=1600&fmt=png-alpha'},
    {storage:'256GB',color:'Glacier',hex:'#dce8ec',price:1830,stock:true,img:'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-18-pro-max-finish-select-glacier-202609?wid=1600&hei=1600&fmt=png-alpha'},
    {storage:'256GB',color:'Burgundy Standard',hex:'#6e2631',price:1830,stock:false,img:'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-18-pro-max-finish-select-burgundy-202609?wid=1600&hei=1600&fmt=png-alpha'}]},
  {id:'ip18p',brand:'iPhone',model:'iPhone 18 Pro',new:true,variants:[
    {storage:'256GB',color:'Glacier',hex:'#dce8ec',price:1590,stock:true,img:'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-18-pro-finish-select-glacier-202609?wid=1600&hei=1600&fmt=png-alpha'},
    {storage:'256GB',color:'Black',hex:'#222',price:1610,stock:true,img:'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-18-pro-finish-select-black-202609?wid=1600&hei=1600&fmt=png-alpha'},
    {storage:'256GB',color:'Burgundy',hex:'#6e2631',price:1640,stock:true,img:'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-18-pro-finish-select-burgundy-202609?wid=1600&hei=1600&fmt=png-alpha'},
    {storage:'512GB',color:'Glacier',hex:'#dce8ec',price:1830,stock:true,img:'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-18-pro-finish-select-glacier-202609?wid=1600&hei=1600&fmt=png-alpha'}]},
  {id:'ip17pm',brand:'iPhone',model:'iPhone 17 Pro Max',offer:true,variants:[
    {storage:'256GB',color:'Blue',hex:'#253c5c',price:1360,old:1450,stock:true,img:'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-17-pro-max-finish-select-deepblue-202509?wid=1600&hei=1600&fmt=png-alpha'},
    {storage:'256GB',color:'Orange',hex:'#c85b2f',price:1360,old:1450,stock:true,img:'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-17-pro-max-finish-select-cosmicorange-202509?wid=1600&hei=1600&fmt=png-alpha'},
    {storage:'512GB',color:'Blue',hex:'#253c5c',price:1600,stock:true,img:'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-17-pro-max-finish-select-deepblue-202509?wid=1600&hei=1600&fmt=png-alpha'},
    {storage:'512GB',color:'Orange',hex:'#c85b2f',price:1600,stock:true,img:'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-17-pro-max-finish-select-cosmicorange-202509?wid=1600&hei=1600&fmt=png-alpha'}]},
  {id:'ip17p',brand:'iPhone',model:'iPhone 17 Pro',variants:[
    {storage:'256GB',color:'Orange',hex:'#c85b2f',price:1260,stock:true,img:'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-17-pro-finish-select-cosmicorange-202509?wid=1600&hei=1600&fmt=png-alpha'},
    {storage:'512GB',color:'Orange',hex:'#c85b2f',price:1480,stock:true,img:'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-17-pro-finish-select-cosmicorange-202509?wid=1600&hei=1600&fmt=png-alpha'}]},
  {id:'ip17',brand:'iPhone',model:'iPhone 17',new:true,variants:[
    {storage:'256GB',color:'Black',hex:'#1f1f1f',price:1065,stock:true,img:'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-17-finish-select-black-202509_GEO_US?wid=1600&hei=1600&fmt=png-alpha'},
    {storage:'256GB',color:'Blue',hex:'#7897ba',price:1065,stock:true,img:'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-17-finish-select-mistblue-202509_GEO_US?wid=1600&hei=1600&fmt=png-alpha'},
    {storage:'256GB',color:'Sage',hex:'#a8b7a0',price:1065,stock:true,img:'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-17-finish-select-sage-202509_GEO_US?wid=1600&hei=1600&fmt=png-alpha'},
    {storage:'256GB',color:'Lavender',hex:'#cfc2df',price:1065,stock:true,img:'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-17-finish-select-lavender-202509_GEO_US?wid=1600&hei=1600&fmt=png-alpha'}]},
  {id:'ip16',brand:'iPhone',model:'iPhone 16',variants:[{storage:'128GB',color:'Ultramarine',hex:'#4b61a0',price:910,stock:true,img:'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-16-finish-select-ultramarine-202409?wid=1600&hei=1600&fmt=png-alpha'}]},
  {id:'ip15',brand:'iPhone',model:'iPhone 15',variants:[{storage:'128GB',color:'Blue',hex:'#6d87b5',price:810,stock:true,img:'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-15-finish-select-202309-6-1inch-blue?wid=1600&hei=1600&fmt=png-alpha'}]},
  {id:'s26u',brand:'Samsung',model:'Galaxy S26 Ultra',new:true,offer:true,variants:[{storage:'512GB',color:'Titanium Gray',hex:'#777',price:1185,old:1290,stock:true,img:'https://images.samsung.com/be/smartphones/galaxy-s26-ultra/images/galaxy-s26-ultra-features-kv.jpg?imbypass=true'}]},
  {id:'s26p',brand:'Samsung',model:'Galaxy S26 Plus',new:true,variants:[{storage:'256GB',color:'Icy Blue',hex:'#a8c7df',price:920,stock:true,img:'https://images.samsung.com/be/smartphones/galaxy-s26-ultra/images/galaxy-s26-ultra-features-kv.jpg?imbypass=true'}]},
  {id:'zflip8',brand:'Samsung',model:'Galaxy Z Flip 8',new:true,variants:[{storage:'256GB',color:'Coral',hex:'#d88d7e',price:1080,stock:true,img:'https://images.samsung.com/is/image/samsung/assets/es/2407/mpdp/b6/galaxy-z-flip6-share-image.jpg'}]},
  {id:'zfold8',brand:'Samsung',model:'Galaxy Z Fold 8 Ultra',new:true,variants:[{storage:'256GB',color:'Navy',hex:'#273a57',price:1800,stock:true,img:'https://images.samsung.com/be/smartphones/galaxy-s26-ultra/images/galaxy-s26-ultra-features-kv.jpg?imbypass=true'}]},
  {id:'s25u',brand:'Samsung',model:'Galaxy S25 Ultra',variants:[{storage:'256GB',color:'Titanium Silverblue',hex:'#8b9bad',price:930,stock:true,img:'https://images.samsung.com/is/image/samsung/p6pim/ar/sm-s938bzblaro/gallery/ar-galaxy-s25-ultra-s938-sm-s938bzblaro-thumb-549045817'}]},
  {id:'s25',brand:'Samsung',model:'Galaxy S25',variants:[{storage:'256GB',color:'Mint',hex:'#b6cfbd',price:770,stock:true,img:'https://images.samsung.com/is/image/samsung/p6pim/mx/sm-s931blbmltm/gallery/mx-galaxy-s25-sm-s931-541005-sm-s931blbmltm-thumb-547930823'}]},
  {id:'s25fe',brand:'Samsung',model:'Galaxy S25 FE',variants:[{storage:'256GB',color:'Black',hex:'#222',price:665,stock:true,img:'https://images.samsung.com/is/image/samsung/p6pim/mx/sm-s731bzkmltm/gallery/mx-galaxy-s25-fe-sm-s731-sm-s731bzkmltm-thumb-549045817'}]},
  {id:'a57',brand:'Samsung',model:'Galaxy A57 5G',variants:[{storage:'256GB',color:'Awesome Gray',hex:'#777',price:525,stock:true,img:'https://images.samsung.com/is/image/samsung/assets/us/smartphones/galaxy-a57-5g/03202026/A57_03-1_FT02-Design_MO.jpg'}]},
  {id:'a56',brand:'Samsung',model:'Galaxy A56 5G',variants:[{storage:'256GB',color:'Awesome Lime',hex:'#c4d76a',price:530,stock:true,img:'https://images.samsung.com/is/image/samsung/p6pim/br/sm-a566ezkazto/gallery/br-galaxy-a56-5g-sm-a566-540642-sm-a566ezkazto-thumb-545718313'}]},
  {id:'a37',brand:'Samsung',model:'Galaxy A37 5G',variants:[{storage:'256GB',color:'Awesome Black',hex:'#222',price:475,stock:true,img:'https://images.samsung.com/is/image/samsung/assets/us/smartphones/galaxy-a37-5g/03242026/A37_FT02_KV_Handriser_MO.jpg?%24ORIGIN_JPG%24='}]},
  {id:'a36',brand:'Samsung',model:'Galaxy A36 5G',variants:[{storage:'256GB',color:'Awesome White',hex:'#eee',price:435,stock:true,img:'https://images.samsung.com/is/image/samsung/p6pim/mx/sm-a366ezsmltm/gallery/mx-galaxy-a36-5g-sm-a366-sm-a366ezsmltm-thumb-546060785'}]},
  {id:'a27',brand:'Samsung',model:'Galaxy A27 5G',variants:[{storage:'256GB',color:'Awesome Blue',hex:'#45638f',price:445,stock:true,img:'https://images.samsung.com/is/image/samsung/assets/us/smartphones/galaxy-a37-5g/03242026/A37_FT02_KV_Handriser_MO.jpg?%24ORIGIN_JPG%24='}]},
  {id:'a17',brand:'Samsung',model:'Galaxy A17',variants:[{storage:'128GB',color:'Black',hex:'#222',price:280,stock:true,img:'https://assets.kmart.com.au/transform/86f0b3ac-987a-4385-a906-577db7be6796/43675838-1?io=transform:extend,width:1100,height:1100&quality=90'}]},
  {id:'a16',brand:'Samsung',model:'Galaxy A16',variants:[{storage:'128GB',color:'Black',hex:'#222',price:290,stock:true,img:'https://images.samsung.com/is/image/samsung/p6pim/mx/sm-a165mzkaltm/gallery/mx-galaxy-a16-sm-a165-sm-a165mzkaltm-544305569?$Q90_1248_936_F_PNG$'}]},
  {id:'a07',brand:'Samsung',model:'Galaxy A07',variants:[{storage:'128GB',color:'Black',hex:'#222',price:290,stock:true,img:'https://images.samsung.com/is/image/samsung/p6pim/mx/sm-a075mzkaltm/gallery/mx-galaxy-a07-sm-a075-569913-sm-a075mzkaltm-thumb-549785654'}]}
];
const fallback={iPhone:'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-17-finish-select-lavender-202509_GEO_US?wid=1200&hei=1200&fmt=png-alpha',Samsung:'https://images.samsung.com/be/smartphones/galaxy-s26-ultra/images/galaxy-s26-ultra-features-kv.jpg?imbypass=true'};
let cart=JSON.parse(localStorage.getItem('lclip-cart')||'[]');
let state={search:'',brands:[],storages:[],max:1900,offers:false,sort:'relevance'};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const ars=n=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(n*USD_TO_ARS);
const usd=n=>'USD '+n.toLocaleString('en-US');
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function imgFallback(img,brand){if(!img.dataset.failed){img.dataset.failed='1';img.src=fallback[brand]}}
function firstAvailable(p){return p.variants.find(v=>v.stock)||p.variants[0]}
function renderStorageFilters(){const ss=[...new Set(products.flatMap(p=>p.variants.map(v=>v.storage)))].sort((a,b)=>parseInt(a)-parseInt(b));$('#storageFilters').innerHTML=ss.map(s=>`<label class="check"><input type="checkbox" value="${s}" data-filter="storage"> ${s}</label>`).join('')}
function filteredProducts(){let list=products.filter(p=>{const v=firstAvailable(p);if(state.brands.length&&!state.brands.includes(p.brand))return false;if(state.storages.length&&!p.variants.some(x=>state.storages.includes(x.storage)))return false;if(v.price>state.max)return false;if(state.offers&&!p.offer)return false;if(state.search&&!(`${p.brand} ${p.model}`.toLowerCase().includes(state.search.toLowerCase())))return false;return true});if(state.sort==='low')list.sort((a,b)=>firstAvailable(a).price-firstAvailable(b).price);if(state.sort==='high')list.sort((a,b)=>firstAvailable(b).price-firstAvailable(a).price);if(state.sort==='new')list.sort((a,b)=>(b.new?1:0)-(a.new?1:0));return list}
function cardHTML(p,featured=false){const v=firstAvailable(p);const storages=[...new Set(p.variants.map(x=>x.storage))];const colors=p.variants.filter(x=>x.storage===v.storage);const interest=5+Math.floor(Math.random()*39);return `<article class="${featured?'mini-card':'product-card'}" data-id="${p.id}">${featured?`<div class="mini-img"><img src="${v.img}" alt="${p.model}" onerror="imgFallback(this,'${p.brand}')"></div><h3>${p.model}</h3><p>${v.storage} · ${v.color}</p><div class="mini-price">${usd(v.price)}</div><div class="mini-ars">${ars(v.price)}</div><button class="primary-btn" data-add="${p.id}">Agregar</button>`:`<div class="product-media"><span class="badge ${p.offer?'offer':''}">${p.offer?'OFERTA':p.new?'NUEVO':''}</span><button class="favorite" aria-label="Favorito">♡</button><img src="${v.img}" alt="${p.model} ${v.color}" onerror="imgFallback(this,'${p.brand}')"></div><div class="product-info"><span class="product-brand">${p.brand}</span><h3>${p.model}</h3><span class="meta">${v.storage} · ${v.color}</span><div class="swatches">${colors.map((c,i)=>`<button class="swatch ${i===0?'active':''}" title="${c.color}" style="background:${c.hex}" data-variant="${p.id}|${c.storage}|${c.color}"></button>`).join('')}</div><div class="storage-row">${storages.map(s=>`<button class="storage-btn ${s===v.storage?'active':''}" data-storage="${p.id}|${s}">${s}</button>`).join('')}</div><div class="price-row">${v.old?`<div class="old-price">${usd(v.old)}</div>`:''}<div class="price">${usd(v.price)}</div><div class="ars">${ars(v.price)} aprox.</div><div class="interest"><i></i>${interest} interesados recientemente</div><div class="card-actions"><button class="primary-btn" data-add="${p.id}">Agregar al carrito</button><button class="quick-btn" data-quick="${p.id}">Ver</button></div></div></div>`}</article>`}
function renderFeatured(){const picks=products.filter(p=>p.offer||p.new).slice(0,4);$('#featuredGrid').innerHTML=picks.map(p=>cardHTML(p,true)).join('')}
function renderProducts(){const list=filteredProducts();$('#productGrid').innerHTML=list.map(p=>cardHTML(p)).join('');$('#resultCount').textContent=`${list.length} modelos disponibles`;$('#emptyState').hidden=list.length>0}
function selectedVariant(p,storage,color){return p.variants.find(v=>v.storage===storage&&v.color===color)||firstAvailable(p)}
function addToCart(id,storage,color){const p=products.find(x=>x.id===id);const v=selectedVariant(p,storage,color);if(!v.stock){toast('Esta variante está sin stock');return}const key=`${id}|${v.storage}|${v.color}`;const existing=cart.find(x=>x.key===key);if(existing)existing.qty++;else cart.push({key,id,qty:1,storage:v.storage,color:v.color});saveCart();toast('Agregado al carrito ✓')}
function saveCart(){localStorage.setItem('lclip-cart',JSON.stringify(cart));renderCart()}
function cartLines(){return cart.map(x=>{const p=products.find(p=>p.id===x.id);const v=selectedVariant(p,x.storage,x.color);return {...x,p,v}}).filter(x=>x.p)}
function renderCart(){const lines=cartLines();$('#cartCount').textContent=lines.reduce((s,x)=>s+x.qty,0);$('#cartItems').innerHTML=lines.length?lines.map(x=>`<div class="cart-item"><img src="${x.v.img}" alt="${x.p.model}" onerror="imgFallback(this,'${x.p.brand}')"><div><h4>${x.p.model}</h4><p>${x.v.storage} · ${x.v.color}</p><div class="qty"><button data-qty="${x.key}|-1">−</button><span>${x.qty}</span><button data-qty="${x.key}|1">+</button></div></div><div><strong>${usd(x.v.price*x.qty)}</strong><button class="remove" data-remove="${x.key}">Eliminar</button></div></div>`).join(''):`<div class="empty-state"><div style="font-size:38px">🛒</div><p>Tu carrito está vacío.</p><a class="primary-btn small" href="#catalogo" id="goCatalog">Ver celulares</a></div>`;const total=lines.reduce((s,x)=>s+x.v.price*x.qty,0);$('#cartTotalUsd').textContent=usd(total);$('#cartTotalArs').textContent=ars(total)}
function openCart(){renderCart();$('#cartDrawer').classList.add('open');$('#drawerBackdrop').classList.add('open')}
function closeCart(){$('#cartDrawer').classList.remove('open');$('#drawerBackdrop').classList.remove('open')}
function openModal(html){$('#modalContent').innerHTML=`<button class="modal-close" id="modalClose">×</button>${html}`;$('#modal').classList.add('open');$('#modalClose').onclick=()=>$('#modal').classList.remove('open')}
function quickView(id){const p=products.find(x=>x.id===id),v=firstAvailable(p);openModal(`<div class="quick-detail"><div class="visual"><img src="${v.img}" alt="${p.model}" onerror="imgFallback(this,'${p.brand}')"></div><div class="detail"><span class="product-brand">${p.brand}</span><h2>${p.model}</h2><p class="meta">${v.storage} · ${v.color}</p><div class="price">${usd(v.price)}</div><div class="ars">${ars(v.price)} aprox.</div><p style="font-size:12px;line-height:1.6;color:#777">Elegí tu variante y agregalo al carrito para coordinar la compra.</p><button class="primary-btn wide" data-add="${p.id}">Agregar al carrito</button></div></div>`)}
function openCheckout(){const lines=cartLines();if(!lines.length){toast('Agregá al menos un producto');return}const total=lines.reduce((s,x)=>s+x.v.price*x.qty,0);openModal(`<div class="modal-inner"><span class="kicker">CHECKOUT</span><h2 style="font-size:30px;letter-spacing:-.05em;margin:8px 0 5px">Finalizá tu pedido</h2><p style="font-size:11px;color:#777;margin-bottom:20px">Completá tus datos y luego coordinamos el pago y la entrega.</p><form class="checkout-form" id="checkoutForm"><label>Nombre y apellido<input required name="name" autocomplete="name"></label><label>Celular<input required name="phone" inputmode="tel"></label><label>Email<input required type="email" name="email"></label><label>CUIT<input required name="cuit" inputmode="numeric"></label><label class="full">Dirección<input required name="address"></label><label>Número<input required name="number"></label><label>Entre calles<input name="between"></label><label>Provincia<select name="province"><option>CABA</option><option>Buenos Aires</option><option>Córdoba</option><option>Santa Fe</option><option>Mendoza</option><option>Otra</option></select></label><label>Código postal<input required name="postal"></label><div class="full" style="display:flex;justify-content:space-between;align-items:center;background:#f7f7f7;padding:14px;border-radius:12px"><span style="font-size:11px">Total del pedido</span><strong>${usd(total)} · ${ars(total)}</strong></div><button class="primary-btn wide full" type="submit">Enviar pedido por WhatsApp</button></form></div>`);$('#checkoutForm').onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));const text=`Hola LclipStore, quiero realizar un pedido. Nombre: ${data.name}. Celular: ${data.phone}. Email: ${data.email}. CUIT: ${data.cuit}. Dirección: ${data.address} ${data.number}, entre ${data.between||'-'}, ${data.province}, CP ${data.postal}. Total: ${usd(total)} (${ars(total)}).`;window.open(`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(text)}`,'_blank');localStorage.removeItem('lclip-cart');cart=[];renderCart();$('#modal').classList.remove('open');closeCart();toast('Pedido preparado para WhatsApp ✓')}}
function resetFilters(){state={search:'',brands:[],storages:[],max:1900,offers:false,sort:'relevance'};$('#searchInput').value='';$('#mobileSearchInput').value='';$$('[data-filter="brand"],[data-filter="storage"]').forEach(i=>i.checked=false);$('#priceRange').value=1900;$('#priceValue').textContent='USD 1.900';$('#offerOnly').checked=false;renderProducts()}
function bind(){renderStorageFilters();renderFeatured();renderProducts();renderCart();$('#year').textContent=new Date().getFullYear();
  $('#searchInput').oninput=e=>{state.search=e.target.value;$('#mobileSearchInput').value=e.target.value;renderProducts()};$('#mobileSearchInput').oninput=e=>{state.search=e.target.value;$('#searchInput').value=e.target.value;renderProducts()};$('#sortSelect').onchange=e=>{state.sort=e.target.value;renderProducts()};$('#priceRange').oninput=e=>{state.max=+e.target.value;$('#priceValue').textContent=usd(state.max);renderProducts()};$('#offerOnly').onchange=e=>{state.offers=e.target.checked;renderProducts()};$('#clearFilters').onclick=resetFilters;$('#emptyReset').onclick=resetFilters;
  document.addEventListener('change',e=>{if(e.target.matches('[data-filter="brand"]')){state.brands=$$('[data-filter="brand"]:checked').map(x=>x.value);renderProducts()}if(e.target.matches('[data-filter="storage"]')){state.storages=$$('[data-filter="storage"]:checked').map(x=>x.value);renderProducts()}});
  document.addEventListener('click',e=>{const add=e.target.closest('[data-add]');if(add){addToCart(add.dataset.add);return}const quick=e.target.closest('[data-quick]');if(quick){quickView(quick.dataset.quick);return}const rm=e.target.closest('[data-remove]');if(rm){cart=cart.filter(x=>x.key!==rm.dataset.remove);saveCart();return}const qty=e.target.closest('[data-qty]');if(qty){const [key,delta]=qty.dataset.qty.split('|');const line=cart.find(x=>x.key===key);if(line){line.qty+=+delta;if(line.qty<1)cart=cart.filter(x=>x!==line);saveCart()}return}const variant=e.target.closest('[data-variant]');if(variant){const [id,storage,color]=variant.dataset.variant.split('|');const p=products.find(x=>x.id===id);const v=selectedVariant(p,storage,color);const card=variant.closest('.product-card');card.querySelector('img').src=v.img;card.querySelector('.price').textContent=usd(v.price);card.querySelector('.ars').textContent=ars(v.price)+' aprox.';card.querySelector('.meta').textContent=`${v.storage} · ${v.color}`;card.querySelectorAll('.swatch').forEach(s=>s.classList.remove('active'));variant.classList.add('active');card.querySelectorAll('.storage-btn').forEach(s=>s.classList.toggle('active',s.dataset.storage===`${id}|${storage}`));return}const st=e.target.closest('[data-storage]');if(st){const [id,storage]=st.dataset.storage.split('|');const p=products.find(x=>x.id===id);const v=firstAvailable({...p,variants:p.variants.filter(x=>x.storage===storage)});const card=st.closest('.product-card');card.querySelector('img').src=v.img;card.querySelector('.price').textContent=usd(v.price);card.querySelector('.ars').textContent=ars(v.price)+' aprox.';card.querySelector('.meta').textContent=`${v.storage} · ${v.color}`;card.querySelectorAll('.storage-btn').forEach(s=>s.classList.toggle('active',s===st));return}});
  $('#cartBtn').onclick=openCart;$('#closeCart').onclick=closeCart;$('#drawerBackdrop').onclick=closeCart;$('#checkoutBtn').onclick=openCheckout;
  $('#accountBtn').onclick=()=>$('#accountMenu').classList.toggle('open');document.addEventListener('click',e=>{if(!e.target.closest('.account-wrap'))$('#accountMenu').classList.remove('open')});$('#openLogin').onclick=()=>{openModal(`<div class="modal-inner"><span class="kicker">LCLIPSTORE</span><h2 style="font-size:28px;margin:7px 0">Iniciar sesión</h2><form id="loginForm"><label style="font-size:10px;font-weight:800">Email<input style="display:block;width:100%;margin:5px 0 12px;padding:11px;border:1px solid #ddd;border-radius:10px" type="email" required></label><label style="font-size:10px;font-weight:800">Contraseña<input style="display:block;width:100%;margin:5px 0 12px;padding:11px;border:1px solid #ddd;border-radius:10px" type="password" required></label><button class="primary-btn wide">Ingresar</button><p id="loginError" style="color:#b42318;font-size:10px"></p></form></div>`);$('#loginForm').onsubmit=e=>{e.preventDefault();$('#loginError').textContent='Usuario o contraseña no encontrados'}};$('#openRegister').onclick=()=>openModal(`<div class="modal-inner"><span class="kicker">LCLIPSTORE</span><h2 style="font-size:28px;margin:7px 0">Crear cuenta</h2><p style="font-size:11px;color:#777">Podés comprar sin crear una cuenta.</p><button class="secondary-btn wide" onclick="document.getElementById('modal').classList.remove('open')">Continuar como invitado</button></div>`);
  $('#mobileMenuBtn').onclick=()=>$('#mainNav').classList.toggle('open');$('#filterToggle').onclick=()=>{$('#filters').classList.add('open');$('#filterBackdrop').classList.add('open')};$('#closeFilters').onclick=()=>{$('#filters').classList.remove('open');$('#filterBackdrop').classList.remove('open')};$('#filterBackdrop').onclick=()=>{$('#filters').classList.remove('open');$('#filterBackdrop').classList.remove('open')};
  $('#calcShipping').onclick=()=>{const p=$('#province').value,cp=$('#postal').value.trim();if(!p&&!cp){$('#shippingResult').textContent='Elegí una provincia o ingresá un CP.';return}const free=p==='CABA'||p==='Buenos Aires'||/^1/.test(cp);if(free)$('#shippingResult').innerHTML='<strong>Envío estimado: GRATIS</strong><br>Zona CABA/GBA · Entrega en el día sujeta a coordinación.';else $('#shippingResult').innerHTML='<strong>Estimación: $4.500–$8.500 ARS</strong><br>Plazo orientativo: 3 a 5 días hábiles. El costo final se confirma con la tienda.'};
  $('#whatsappBtn').onclick=()=>window.open(`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent('Hola LclipStore, quiero consultar por un celular.')}`,'_blank');
  $('#acceptCookies').onclick=()=>{localStorage.setItem('lclip-cookies','1');$('#cookie').style.display='none'};$('#rejectCookies').onclick=()=>{localStorage.setItem('lclip-cookies','0');$('#cookie').style.display='none'};if(localStorage.getItem('lclip-cookies'))$('#cookie').style.display='none';
  $('#regretBtn').onclick=()=>openModal(`<div class="modal-inner"><span class="kicker">GESTIÓN DE COMPRA</span><h2 style="font-size:28px">Botón de arrepentimiento</h2><p style="font-size:11px;color:#777">Completá el formulario y la tienda podrá gestionar tu solicitud conforme a la normativa aplicable.</p><form class="checkout-form"><label>Nombre<input required></label><label>Email<input type="email" required></label><label class="full">Número de pedido<input required></label><label class="full">Motivo<textarea style="width:100%;min-height:90px;border:1px solid #ddd;border-radius:10px;margin-top:5px"></textarea></label><button class="primary-btn full">Enviar solicitud</button></form></div>`);
  $('#privacyBtn').onclick=()=>openModal(`<div class="modal-inner"><h2>Privacidad</h2><p style="font-size:12px;color:#777;line-height:1.7">LclipStore debe completar este texto con su política de privacidad real antes de publicar la web.</p></div>`);$('#termsBtn').onclick=()=>openModal(`<div class="modal-inner"><h2>Términos y condiciones</h2><p style="font-size:12px;color:#777;line-height:1.7">LclipStore debe completar este texto con sus condiciones comerciales reales antes de publicar la web.</p></div>`);
}
bind();


